
##################################################################################################
# You'll need to fill in a few bits of information and copy this file to application.yml
# - client ID and client secret
# - okta preview domain (dev-123456.oktapreview.com) to accessTokenUri and userInfoUri
# - custom domain to userAuthorizationUri
##################################################################################################

security:
    oauth2:
        client:
            # From Okta application
            clientId: "< You Okta app client ID >"
            clientSecret: "< Your Okta app client secret >"
            accessTokenUri: https://< Your dev-* Okta preview domain >.oktapreview.com/oauth2/default/v1/token
            # This has to be the custom URL or the custom sign-in page won't be visible
            userAuthorizationUri: https://< Your custom domain >/oauth2/default/v1/authorize
            scope: openid profile email
        resource:
            userInfoUri: https://< Your dev-* Okta preview domain >.oktapreview.com/oauth2/default/v1/userinfo
        sso:
            loginPath: /authorization-code/callback